main:
  - name: Hallo
    pageRef: /
    weight: 10
#  - name: Ãœber mich
#    pageRef: /about
#    weight: 65
  - name: Consulting
    pageRef: /consulting
    weight: 30
  - name: Projekte
    pageRef: /consulting/projects
    weight: 40
  - name: CV
    pageRef: /consulting/cv
    weight: 45
#  - name: DenktMit
#    pageRef: /denktmit
#    weight: 50
  - name: Blog
    pageRef: /blog
    weight: 60
  - name: Kontakt
    pageRef: /contact
    weight: 70
#    - name: Tags
#      pageRef: /tags
#      weight: 30
