services:
  selenium-chrome:
    image: seleniarm/standalone-chromium:124.0
    platform: linux/arm64/v8
    container_name: seleniarm-chromium
    shm_size: 2gb
    ports:
      - "4444:4444"
    extra_hosts:
      - "host.docker.internal:host-gateway"
